// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.MoonriseMoonset
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("coordinates")]
        public Coordinates Coordinates { get; set; }

        [JsonProperty("phase")]
        public string Phase { get; set; }

        [JsonProperty("moonrise")]
        public DateTimeOffset Moonrise { get; set; }

        [JsonProperty("moonset")]
        public DateTimeOffset Moonset { get; set; }

        [JsonProperty("moonAlwaysUp")]
        public bool MoonAlwaysUp { get; set; }

        [JsonProperty("moonAlwaysDown")]
        public bool MoonAlwaysDown { get; set; }
    }

    public partial class Coordinates
    {
        [JsonProperty("latitude")]
        public double Latitude { get; set; }

        [JsonProperty("longitude")]
        public double Longitude { get; set; }
    }
}
